### ISSUE TITLE
小众软件不支持在当前标签页打开  http://www.appinn.com/fastwindowswitcher/

### ISSUE THREAD

**Issue by ghost** [ansonhorse/chrome-smart-link#1]

**Comment by ansonhorse** [comment]
@sgrjyb 不好意思，这个小扩展也有一段时间没看了。
你说的这个链接，暂时是打不开

**Comment by ghost** [comment]
@ansonhorse  [bilibili搜索框在新标签打开](https://www.bilibili.com/index.html)

**Comment by ansonhorse** [comment]
@ b站搜索的建议选项链接，就算Smart Link去干预它的行为，也是没什么用的，因为它也是页面js来控制打开页面的，本身链接是这样的：
```html
<a>建议关键词</a>
```
这种链接，如果没有绑定js事件，点击它是没有任何反应的。注意这跟
```html
<a href="">text</a>
```
是有区别的，`href=""`指向的是当前页面的url。

从0.3.87开始，Smart Link将会不干预这种链接的行为。
