### ISSUE TITLE
设置为在当前标签页打开 添加元素规则以后 一些网站会在新标签页打开  javascript:void(0)链接会跳转到https://pan.baidu.com/javascript:void(0); 怎么解决

### ISSUE THREAD

**Issue by ghost** [ansonhorse/chrome-smart-link#3]

**Comment by ansonhorse** [comment]
@sgrjyb 这个是已知的bug，待我整理一下代码

**Comment by ghost** [comment]
@ansonhorse  为什么添加元素后 规则在当前标签页打开 还是会在新标签页打开 ? 希望早点更新

**Comment by ghost** [comment]
@ansonhorse  推荐你用这个扩展[Right Click Opens Link in New Tab](https://chrome.google.com/webstore/detail/right-click-opens-link-in/afalkcagoidkdjdlfoaicbanbfgoamoo) 然后把所有标签页设置为在当前标签页打开

**Comment by sgrjyb** [comment]
@ansonhorse  这个网站不能设置为在新标签页打开 [ tingting520店铺](http://tingting060707.aliyizhan.net) , 怎么设置 ?

**Comment by ansonhorse** [comment]
@sgrjyb 
你是说为某个区块添加规则，但是没有效果？不妨发一下链接，还有区块选择器。

[Right Click Opens Link in New Tab](https://chrome.google.com/webstore/detail/right-click-opens-link-in/afalkcagoidkdjdlfoaicbanbfgoamoo)这个我也有试用过，不过不太适合我。而我写的这个小扩展，也只是解决一些自己的小需求而已。

你下面说的这个，应该是一个专门给移动终端使用的网页应用，你可以用F12的Element查看一下，其实它并没有真正意义上的超链接，打开页面或者跳转，应该是javascript控制的。而[Smart Link](https://github.com/ansonhorse/chrome-smart-link/) 针对的是**link**。

**Comment by ghost** [comment]
![xiami](https://user-images.githubusercontent.com/28247198/31317960-b62781a2-ac7c-11e7-83b4-d55875cd3886.PNG)

**Comment by ghost** [comment]
javascript控制的 应该用什么好 ? 一个网站有两个规则 会冲突吗 ?

**Comment by ansonhorse** [comment]
@sgrjyb a.bt_play，具体在哪个页面存在这种链接呢，首页没看到有。

javascript控制的，这个我不清楚。

一个超链接，最终只会应用到一个规则。

**Comment by ghost** [comment]
像 javascript链接 怎么办 ?  虾米 我的音乐 播放按钮 a.bt_play

**Comment by ansonhorse** [comment]
@sgrjyb 不好意思，暂时扩展的设计是：不修改href不是普通url的链接的打开行为。比如这个a.bt_play，也就是“播放选中歌曲”按钮，实际上它的行为是由它所在的页面的javascript来控制的，它会打开一个新页面，是页面里的javascript所处理呈现的结果。

**Comment by ghost** [comment]
@ 我的音乐点击播放会跳转到 http://www.xiami.com/javascript:void(0); 和打开播放

虾米音乐 不创建元素 就不能收藏 歌曲 你试试

**Comment by ansonhorse** [comment]
最新版本是0.3.85，刚刚发布了，到时候你可以更新试试看这个bug是否有修复。

如果特定到你想要改变“播放选中歌曲”按钮的打开链接的方式这个情况，有一个简单粗暴的方法：
```javascript
window.open = function (url) {
  window.location.href = url;
};
```
可以在Tampermonkey里写一个小脚本。

**Comment by sgrjyb** [comment]
window.open = function (url) {
  window.location.href = url
};   怎么做 ?

**Comment by ghost** [comment]
``` js
window.open = function (url) {
  window.location.href = url;
};
```
哈哈

**Comment by ansonhorse** [comment]
新版0.3.85已发布成功。
虾米这个，你可以在Tampermonkey添加如下脚本。
```javascript
// ==UserScript==
// @name         虾米音乐 播放选中歌曲 本页打开
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://www.xiami.com/*
// @grant        none
// ==/UserScript==

(function() {
  'use strict';
	var script = document.createElement('script');
	script.type = "text/javascript";
	script.id = 'xiami-injected';
	script.innerHTML = `
		// 添加歌曲
		function addSongs(str) {
			if (!isIE() && !!document.createElement('audio').canPlayType) {
				if ($.cookie('XMPLAYER_isOpen') != '1') {
					// 原
					// window.open('http://www.xiami.com/play?ids=' + str + '#open', 'xiamiMusicPlayer');
					window.location.href = 'http://www.xiami.com/play?ids=' + str + '#open';
				}
				document.cookie = 'XMPLAYER_url='+ str +';path=/;domain=.xiami.com';
				document.cookie = 'XMPLAYER_addSongsToggler=1;path=/;domain=.xiami.com';
			}
			else {
				var playerTrigger = thisMovie('trans');
				if (typeof(playerTrigger.addSongs) === "function") {
					playerTrigger.addSongs(str);
					transclick(str, "add");
				} else {
					setTimeout(function() {
						if (typeof(playerTrigger.addSongs) === "function") {
							playerTrigger.addSongs(str);
							transclick(str, "add");
						} else {
							openOldMusicPlayer(str);
						}
					}, 500);
				}
			}
		}
	`;

	document.body.appendChild(script);
})();
```

**Comment by ansonhorse** [comment]
@sgrjyb 这个其实是重写了网页原来的js，所以如果网页js是有更新的话，比如函数名变了，这个就失效了。或者，函数名没变，但里面的处理变了，那这个重写的函数，就没有最新的效果了。当然可以跟着它的更新来更新这个TM脚本，只需把window.open的方式改为window.location.href即可。

**Comment by ghost** [comment]
[虾米](http://www.xiami.com/) 点击收藏会刷新页面 ! 规则 在当前标签页打开 

![default](https://user-images.githubusercontent.com/28247198/31319088-de74ec9a-ac8f-11e7-81b7-98143ec88af9.PNG)
 
虾米音乐规则不起作用 ,像这种情况怎么 让虾米音乐规则起作用 或者增加 白名单 ?

**Comment by sgrjyb** [comment]
@ansonhorse  https://github.com/tarolabs/sscap/releases 下载文件 会在新标签页打开 https://github.com/tarolabs/sscap/releases/download/sscapv3.5/SSCapV3.5.rar

**Comment by ansonhorse** [comment]
@sgrjyb 
a.wrap这几个链接，都是页面js控制的。
至于下面说打开下载链接会在新标签也打开，我这里并没有发生这个情况。
而且，也很不建议使用正则http://*/*这种，很可能会出现一些不符合你预期的情况，当然可能你是想测试而已。

**Comment by ghost** [comment]
@ansonhorse  虾米音乐首页 点击红心会跳转到 http://www.xiami.com/?spm=a1z1s.6843761.226669510.1.79T4eD
 选择元素没有打开规则创建页面而是进入了 http://www.xiami.com/?spm=a1z1s.6843761.226669510.1.79T4eD

**Comment by ansonhorse** [comment]
@sgrjyb 你可以试试为这些链接添加一个规则，打开方式设为“页面默认规则”

**Comment by ansonhorse** [comment]
关于issue标题所述的问题， javascript:void(0)链接点击的问题，应该是已经修正了，这个issue先就此关闭

**Comment by ghost** [comment]
@ansonhorse 因为虾米存在两个规则 所有第二规则不起作用！　

怎么没有导出功能？

**Comment by ghost** [comment]
@ansonhorse  主要的原因是因为 添加了规则 虾米音乐在当前标签页打开 !

**Comment by ansonhorse** [comment]
@sgrjyb 看来要达到你的需求还是要努力一番啊，或者你需要一个强大的工具？（抱歉我不清楚有没有）

其实我也想尽善尽美，奈何时间精力有限ヽ(￣▽￣)ﾉ。
至于这个导出导入，或许会有的。

**Comment by ghost** [comment]
@ansonhorse  
打开磁力链接会这样 http://xxx.xx/magnet:?xt=urn:btih:45261A083B94C149BB6C12F5937BD2B62ACAA8F6

0.3.87

**Comment by ansonhorse** [comment]
@sgrjyb 建议你提交新的issue进行反映，当前issue已关闭，没提示消息呢。
你发的链接有不和谐内容，我改了，而这个问题有空我会看的。
