### ISSUE TITLE
希望可以增加 白名单 选项 (白名单不启用规则) 

### ISSUE THREAD

**Issue by ghost** [ansonhorse/chrome-smart-link#5]

**Comment by ansonhorse** [comment]
“**打开方式**“里，有一项是“**页面默认规则**”

**Comment by ghost** [comment]
@ansonhorse  我的规则是 https://\*/\*  所以不适合我 ,  再说也没有必要创建 页面默认规则

**Comment by ansonhorse** [comment]
@sgrjyb 或者你可以具体说说你这个白名单的想法。
我的意思是，比如有一个规则是：
`正则表达式, https://*/*, 新标签`
但是比如我不想baidu遵循这个规则，而是使用它页面的规则，那就另外新建一个规则：
`包含, https://www.baidu.com, 页面默认规则`
按照扩展的逻辑，排在前面的规则会先被匹配到，所以后面针对baidu新建的这个规则，应该放在上面的规则之前(抱歉的是，目前还没有拖拽排序功能)

**Comment by ghost** [comment]
@ansonhorse 按添加时间排序
