### ISSUE TITLE
还是小众软件 怎么设置为在当前标签页打开   或者怎么 Tampermonkey 脚本 ?

### ISSUE THREAD

**Issue by ghost** [ansonhorse/chrome-smart-link#6]
http://www.appinn.com/qttabbar/

**Comment by ansonhorse** [comment]
请问页面上哪些链接没有按照设置的规则打开？

**Comment by ansonhorse** [comment]
@sgrjyb 我如图这样设置，小测了一下，没碰到不遵循的。所以最好你指出是哪些链接。
![qq 20171030174324](https://user-images.githubusercontent.com/7548142/32164261-df946360-bd99-11e7-83c3-e71c716c6af8.png)

**Comment by ghost** [comment]
![default](https://user-images.githubusercontent.com/28247198/32164385-57d3386a-bd9a-11e7-92cf-366e18b34ede.PNG)

@ansonhorse

**Comment by ansonhorse** [comment]
其实这个是页面js影响的：
```javascript
$(".entry-content a[rel!='inlinks']").click(function() {
    window.open(this.href);
    return false;
});
```
页面的绑定，应该是在扩展绑定之后执行的，而且页面的绑定用了`return false`（因为它是window.open打开一个页面，所以正常地应该要用`return false`，不然又在当前标签页打开这个链接了），所以链接的点击事件就传递不到扩展这里了，自然也就“失效”了。

至于想用TM解绑页面的监听，大致可以这样：
请引入jQuery
```javascript
$(function () {
  // 延迟一下
  setTimeout(function () {
    // 解绑点击事件监听
    $(".entry-content a[rel!='inlinks']").unbind('click');
  }, 1000);
});
```

**Comment by sgrjyb** [comment]
@ansonhorse  完整的小脚本是 ? 我要将他设置为在当前标签页打开

**Comment by sgrjyb** [comment]
@ansonhorse  怎么修改  不作用弹出窗口 比如    https://www.dropbox.com/login?cont=https%3A%2F%2Fwww.dropbox.com%2Fhome

```js
    window.open = function (url) {
  window.location.href = url;
};

```
