### ISSUE TITLE
蓝奏云，设置为当前标签页打开时，点击下载  没反应

### ISSUE THREAD

**Issue by ghost** [ansonhorse/chrome-smart-link#8]
https://pan.lanzou.com/1874253/
设置为当前标签页打开时，点击下载，没反应。
怎么设置在当前标签页打开 ?

**Comment by ansonhorse** [comment]
```html
<a href="http://abc.com/" onclick="do_sth()">text</a>
```
这种形式，即链接有正常的url，且有onclick方法，扩展暂时是有去处理的。
正常来说，扩展不应该去干预绑定了`onclick`方法的链接的打开方式。

而为什么你贴的链接，使用`当前标签打开`规则时，点击没有反应，是因为扩展虽然有去改变它的打开方式，但是这里有一个安全问题，使用window.location.href在https域名下打开一个不同域名且不是https的url，chrome(测试版本是62，其他未测）会提示不允许。
![22222](https://user-images.githubusercontent.com/7548142/32234261-4523bfe8-be97-11e7-921c-b1faefd1af0a.png)

这个跨域的问题会在接下来的更新中修正，扩展将使用新的方式来处理`当前标签打开`规则的打开方式。

**Comment by ghost** [comment]
@ansonhorse  谢谢

**Comment by ansonhorse** [comment]
多谢你的反馈，不过可惜的是 ，这两个问题是否修正，都不能满足你的这个需求。

**Comment by ghost** [comment]
@ansonhorse 我的需求很简单 在当前标签页打开所有链接

**Comment by ansonhorse** [comment]
你的需求我明白。不过Smart Link暂时没有这种功能，也没有计划增加。
下面这个你可以试试
[Open Link in Same Tab](https://chrome.google.com/webstore/detail/open-link-in-same-tab/kgpefningcojblgciiljmabggbbjiojb)

**Comment by ansonhorse** [comment]
@sgrjyb 有兴趣的可以fork一份，修改达到你的需求的，我估计不难。

**Comment by sgrjyb** [comment]
@ansonhorse  好啊

**Comment by sgrjyb** [comment]
@ansonhorse  Open Link in Same Tab 不如 Smart Link
